language: php

php:
  - 7.0

sudo: false

cache:
  directories:
    - $HOME/.composer/cache

services:
  - postgresql

addons:
  postgresql: '9.4'

before_install:
  - phpenv config-rm xdebug.ini

install:
  - composer self-update
  - composer install --prefer-dist --no-interaction

before_script:
  - psql -U postgres -c 'create database taxes'
  - psql -U postgres -d taxes -c 'create extension postgis'

script:
  - vendor/phpunit/phpunit/phpunit --stop-on-error --stop-on-failure
